# Generated by Django 4.1 on 2022-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime_klijenta", models.TextField()),
                ("ime_zaposlenog", models.TextField()),
                (
                    "izbor_tret",
                    models.CharField(
                        choices=[
                            ("EP", "Estetski pedikir"),
                            ("MP", "Medicinski manikir"),
                            ("EM", "Estetski manikir"),
                        ],
                        default="EP",
                        max_length=2,
                    ),
                ),
                ("napomena", models.TextField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created"],},
        ),
    ]
