# Generated by Django 4.1 on 2022-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_reservation_izbor_tret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="izbor_radnika",
            field=models.CharField(
                choices=[(0, "Ana"), (1, "Kaca"), (2, "Suza")], default=0, max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="ime_klijenta",
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="ime_zaposlenog",
            field=models.TextField(max_length=25),
        ),
    ]
