# Generated by Django 4.1 on 2022-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_reservation_izbor_radnika_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="ime_zaposlenog",),
        migrations.AlterField(
            model_name="reservation",
            name="izbor_radnika",
            field=models.CharField(
                choices=[("Aa", "Ana"), ("Ka", "Kaca"), ("Sa", "Suza")],
                default="Aa",
                max_length=2,
            ),
        ),
    ]
