# Generated by Django 4.1 on 2022-08-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_reservation_ime_zaposlenog_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="updated",),
        migrations.AddField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
