# Generated by Django 4.1 on 2022-08-10 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_reservation_updated_reservation_datum_tret"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation", options={"ordering": ["-datum_tret"]},
        ),
        migrations.RemoveField(model_name="reservation", name="created",),
        migrations.AddField(
            model_name="reservation",
            name="vreme_tret",
            field=models.CharField(
                choices=[
                    ("EP", "Estetski pedikir"),
                    ("MP", "Medicinski pedikir"),
                    ("EM", "Estetski manikir"),
                ],
                default="EP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 8, 10, 8, 46, 26, 918719, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="izbor_radnika",
            field=models.CharField(
                choices=[("A0", "Ana"), ("K1", "Kaca"), ("S2", "Suza")],
                default="A0",
                max_length=2,
            ),
        ),
    ]
