# Generated by Django 4.1 on 2022-08-30 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_reservation_datum_tret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 8, 30, 8, 32, 59, 445881, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="izbor_tretmana",
            field=models.CharField(
                choices=[
                    ("EP", "Estetski pedikir"),
                    ("MP", "Medicinski pedikir"),
                    ("EM", "Estetski manikir"),
                ],
                default="EP",
                max_length=3,
            ),
        ),
    ]
