# Generated by Django 4.1 on 2022-09-05 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_reservation_datum_tret_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation", options={"ordering": ["-datum_tret", "-poc_tret"]},
        ),
        migrations.RemoveField(model_name="reservation", name="vreme_tret",),
        migrations.AddField(
            model_name="reservation",
            name="kraj_tret",
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
        migrations.AddField(
            model_name="reservation",
            name="poc_tret",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 5, 18, 10, 16, 240070, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="napomena",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
