# Generated by Django 4.1 on 2022-09-05 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_reservation_datum_tret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="id",
            field=models.CharField(
                default=None, max_length=3, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 5, 18, 56, 30, 247799, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
