# Generated by Django 4.1 on 2022-09-06 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_pricelist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 6, 8, 32, 7, 333907, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
