# Generated by Django 4.1 on 2022-09-06 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_reservation_datum_tret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="datum_tret",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 6, 8, 39, 58, 351397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
