# Generated by Django 4.1.1 on 2022-09-13 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_reservation_datum_tret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 13, 7, 50, 1, 479564, tzinfo=datetime.timezone.utc)),
        ),
    ]
