# Generated by Django 4.1.1 on 2022-09-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_reservation_datum_tret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
