# Generated by Django 4.1.1 on 2022-09-13 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_klijenta', models.TextField(max_length=25)),
                ('izbor_radnika', models.CharField(choices=[], default='S0', max_length=2)),
                ('izbor_tretmana', models.CharField(choices=[], default='MP', max_length=3)),
                ('cena_izabranog_tretmana', models.IntegerField(default=1000)),
                ('napomena', models.TextField(blank=True, max_length=100)),
                ('datum_tret', models.DateField(default=datetime.datetime(2022, 9, 13, 11, 57, 40, 230729, tzinfo=datetime.timezone.utc))),
                ('poc_tret', models.TimeField(default=datetime.time(8, 0))),
                ('kraj_tret', models.TimeField(default=datetime.time(8, 30))),
            ],
            options={
                'ordering': ['-datum_tret', '-poc_tret'],
            },
        ),
    ]
