# Generated by Django 4.1.1 on 2022-09-13 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_reservation_datum_tret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 13, 16, 26, 35, 957809, tzinfo=datetime.timezone.utc)),
        ),
    ]
