# Generated by Django 4.1.1 on 2022-09-13 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_reservation_datum_tret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 13, 17, 19, 18, 282762, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_tretmana',
            field=models.CharField(choices=[('MP', 'Medicinski pedikir'), ('EP', 'Estetski pedikir')], default='MP', max_length=3),
        ),
    ]
