# Generated by Django 4.1.1 on 2022-09-13 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_reservation_datum_tret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 13, 17, 49, 17, 221546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_radnika',
            field=models.CharField(choices=[('s0', 'suza')], default='s0', max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_tretmana',
            field=models.CharField(choices=[], default='MP', max_length=3),
        ),
    ]
