# Generated by Django 4.1.1 on 2022-09-15 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_reservation_datum_tret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 8, 49, 8, 556607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_tretmana',
            field=models.CharField(choices=[('EP', 'Estetski pedikir'), ('MHP', 'Medicinsko - hiruški pedikir'), ('MP', 'Medicinski Pedikir')], default='MP', max_length=3),
        ),
    ]
