# Generated by Django 4.1.1 on 2022-09-15 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_reservation_datum_tret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datum_tret',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 9, 10, 31, 944183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_radnika',
            field=models.CharField(choices=[('S0', 'Suza'), ('A1', 'Andjela')], default='S0', max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='izbor_tretmana',
            field=models.CharField(choices=[('EP', 'Estetski pedikir'), ('MHP', 'Medicinsko - hiruški pedikir'), ('MP', 'Medicinski Pedikir'), ('SP', 'Spa pedikir')], default='MP', max_length=3),
        ),
    ]
